language: java
jdk: oraclejdk11
script: mvn -e verify
sudo: required
addons:
  chrome: stable
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: dictionary-ru-itpark